---
title: "Computational_6"
author: "Garima Agarwal"
date: "May 14, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(OptionPricing)
library(plyr)

lgm<-function(n){
  m = (2^31) - 1
  a = (7^5)
  x=vector(length = (n+1))
  u=vector(length = n)
  x[1]=as.numeric(Sys.time())
  for(i in 2:(n+1))
  {
    x[i] = (a*x[i - 1])%%m
  }
  u=(x[2:(n+1)] + 0.5)/m
  
  return (u)
}
box<-function(u1,u2){
  z1=((-2*log(u1))^(1/2))*cos(2*pi*u2)
  #z2=((-2*log(u1))^(1/2))*sin(2*pi*u2)
  return(z1)
}
```

#1

```{r Lookback}
lookback<-function(s0,k,T, r,sigma,n, h, nstep){
  stock=matrix(data=1,nrow=(nstep),ncol=(n+1))
  stock[,1]=s0
  call=vector(length = nstep)
  put=vector(length = nstep)
  z1=matrix(nrow=(nstep),ncol=n)
  for(i in 1:(nstep)){
    z1[i,]=box(lgm(n),lgm(n))
    stock[i,2:(n+1)]=exp((r-sigma^2)*h + sigma*sqrt(h)*z1[i,])
    
    stock[i,]=cumprod(stock[i,])
    call[i]=exp(-r*T)*max(max(stock[i,])-k,0)
    put[i]=exp(-r*T)*max(k-min(stock[i,]),0)
  }
  # for(i in ((nstep/2)+1):(nstep)){
  #   
  #   stock[i,2:(n+1)]=exp((r-sigma^2)*h + sigma*sqrt(h)*(-z1[(i-(nstep/2)),]))
  #   stock[i,]=cumprod(stock[i,])
  # }
  
  # for(i in 1:nstep){
  #   call[i]=exp(-r*T)*max(max(stock[i,])-k,0)
  #   put[i]=exp(-r*T)*max(k-min(stock[i,]),0)
  # }
  t=c(mean(call),mean(put))
  return(t)
  
}

s0=98
k=100
s=vector(length = 10)
s[1]=.12
rr=s[1]
i=2

while(rr<.47){
  rr=rr+0.04
  s[i]=rr
  i=i+1
  
}
T=1
r=0.03
n=100
nstep=7000
h=T/n
t=matrix(data=0,nrow=10,ncol=2)
for(i in 1:10){
  t[i,]=lookback(s0,k,T, r,s[i],n, h, nstep)
}
plot(s,t[,1],xlab="Volatility",ylab="Call and Put Prices",type="l",col="Red",ylim=c(5,43))
par(new=TRUE)
plot(s,t[,2],xlab="Volatility",ylab="Call and Put Prices",type="l",col="Blue",ylim=c(5,43))
```

#2

```{r Proj6_2func}
Proj6_2func<-function(lambda1=0.2,lambda2=0.4,T=5){
  v0=20000
  l0=22000
  mu=-0.1
  gamma=-0.4
  r0=0.02
  alpha=0.7
  qt=e=0.95
  delta=0.25
  beta=(e-alpha)/T
  sigma=0.2
  n=T*12
  h=T/n
  R=r0+ delta*lambda2
  r=R/12
  pmt=l0*r/(1-(1/((1+r)^n)))
  qt=vector(length = (n+1))
  qt[1]=alpha
 
  a=pmt/r
  b=pmt/(r*((1+r)^n))
  c=1+r
  nstep=1000
  l=matrix(data=0,nrow=(1),ncol=(n+1))
  q=matrix(data=0,nrow=(n+1),ncol=1)
  stop=matrix(data=0,nrow=(nstep),ncol=(n+1))
  pay=vector(length = nstep)
  l[1]=l0
  for(i in 1:n){
    l[1,(i+1)]=a-(b*(c^(12*h*i)))
    qt[(i+1)]=alpha +(beta*(h*i))
  }
  stock=matrix(data=1,nrow=(nstep),ncol=(n+1))
  stock[,1]=v0
  stoptime=rep(0,nstep)
  event=vector(length = (n+1))
  event[1]=0
  number=vector(length = nstep)
  yyy=vector(length = nstep)
  z1=matrix(nrow=(nstep/2),ncol=n)
  for(i in 1:(nstep/2)){
    z1[i,]=box(lgm(n),lgm(n))
    j=rpois(n,lambda1*h)
    stock[i,2:(n+1)]=exp((r-sigma^2)*h + sigma*sqrt(h)*z1[i,] + (gamma)*j)
    number[i]=sum(j)
    stock[i,]=cumprod(stock[i,])
    stop[i,]=(stock[i,]<=(qt*l))
    
    stoptime[i]=which(stop[i,]>0)[1]
  }
  for(i in ((nstep/2)+1):(nstep)){
    j=rpois(n,lambda1*h)
    stock[i,2:(n+1)]=exp((r-sigma^2)*h + sigma*sqrt(h)*(-z1[(i-(nstep/2)),])+ (gamma)*j)
    number[i]=sum(j)
    stock[i,]=cumprod(stock[i,])
    stop[i,]=(stock[i,]<=(qt*l))
    stoptime[i]=which(stop[i,]>0)[1]
  }
  stoptime[is.na(stoptime)]<-0
  time=vector(length = nstep)
  for(i in 1:nstep){
    event[2:(n+1)]=rpois(n,lambda2*h)
    t=which(event>0)[1]
    
    t[is.na(t)]<-99
    time[i]=t
    if(t<=stoptime[i]){
      yyy[i]=1
      stoptime[i]=t
    }
    if((stoptime[i]==0) && (t!=99)){
      yyy[i]=1
      stoptime[i]=t
    }
  }
 
  prob_default=sum(stoptime>0)/nstep
  for(i in 1:nstep){
    if(stoptime[i]>0){
      if(yyy[i]==1){
        pay[i]=exp(-r*h*stoptime[i])*abs(l[1,stoptime[i]]-e*stock[i,stoptime[i]])
      }else{
        pay[i]=exp(-r*h*stoptime[i])*max((l[1,stoptime[i]]-e*stock[i,stoptime[i]]),0)
      }
    }else{
      pay[i]=0
    }
    
  }
  #expected_stop=mean(stoptime[stoptime>0])/12
  expected_stop=sum(stoptime[stoptime>0])/(12*sum(stoptime>0))
  payout=mean(pay)
  t<-c(payout,prob_default,expected_stop)
  return(t)

  
}
```

```{r Basic_Value}
lambda1=0.2
lambda2=0.4
T=5


abc=Proj6_2func(lambda1,lambda2,T)
abc=as.matrix(abc)
rownames(abc)<-c("Value of Default Option","Default Probability","Expected Exercise Time")
kable(abc,caption="Default Option D")
```

#a

```{r Lambda1_price}
lambda1=vector(length = 8)
y=0.05
lambda1[1]=y
i=2
while(y<0.39){
  y=y+0.05
  lambda1[i]=y
  i=i+1
}
lambda2=0.4
lambda1=as.matrix(lambda1)
tt=c(3,4,5,6,7,8)
payoff_1=matrix(data=0,nrow=8,ncol=length(tt))
prob_1=matrix(data=0,nrow=8,ncol=length(tt))
time_1=matrix(data=0,nrow=8,ncol=length(tt))
tt=as.matrix(tt)
for(i in 1:8){
  ret=apply(tt,1,Proj6_2func,lambda1=lambda1[i],lambda2=0.4)
  payoff_1[i,]=ret[1,]
  prob_1[i,]=ret[2,]
  time_1[i,]=ret[3,]
  plot(tt,ret[1,],type="l",col=i,ylim=c(3000,7000),xlab="Time",
       ylab="Value of Default Option",main="Value of Default Option for different Lambda1")
  par(new=TRUE)
}
par(new=FALSE)
```

```{r Lambda2_price}
lambda2=vector(length = 9)
y=0.00
lambda2[1]=y
i=2
while(y<0.79){
  y=y+0.1
  lambda2[i]=y
  i=i+1
}
lambda1=0.2
payoff_2=matrix(data=0,nrow=9,ncol=length(tt))
prob_2=matrix(data=0,nrow=9,ncol=length(tt))
time_2=matrix(data=0,nrow=9,ncol=length(tt))
for(i in 1:9){
  ret=apply(tt,1,Proj6_2func,lambda1=lambda1,lambda2=lambda2[i])
  payoff_2[i,]=ret[1,]
  prob_2[i,]=ret[2,]
  time_2[i,]=ret[3,]
  plot(tt,ret[1,],type="l",col=i,ylim=c(0,7000),xlab="Time",
       ylab="Value of Default Option",main="Value of Default Option for different Lambda2")
  par(new=TRUE)
}
par(new=FALSE)

```

#b

```{r Lambda1_prob}
for(i in 1:8){
  plot(tt,prob_1[i,],col=i,ylim = c(0.5,1),type="l",xlab="Time",
       ylab="Default Probability",main="Default Probability for different Lambda1")
  par(new=TRUE)
}
par(new=FALSE)
```

```{r Lambda2_prob}
for(i in 1:9){
  plot(tt,prob_2[i,],col=i,ylim = c(0,1),type="l",xlab="Time",
       ylab="Default Probability",main="Default Probability for different Lambda2")
  par(new=TRUE)
}
par(new=FALSE)
```

#c

```{r Lambda1_Time}
for(i in 1:8){
  plot(tt,time_1[i,],col=i,ylim = c(0.5,2.5),type="l",xlab="Time",
       ylab="Expected Exercise Time",main="Expected Exercise Time for different Lambda1")
  par(new=TRUE)
}
par(new=FALSE)
```

```{r Lambda2_Time}
for(i in 1:9){
  plot(tt,time_2[i,],col=i,ylim = c(0.5,2.5),type="l",xlab="Time",
       ylab="Expected Exercise Time",main="Expected Exercise Time for different Lambda1")
  par(new=TRUE)
}
par(new=FALSE)
```
